"""ToonzScript Generator

Generates ToonzScript (.toonzscript) files that can be executed by OpenToonz
to create scene files and perform other operations.
"""

import os


class ToonzScriptGenerator:
    """Generates ToonzScript code for OpenToonz operations."""
    
    def __init__(self):
        """Initialize the generator."""
        self._lines = []
    
    def clear(self):
        """Clear the current script."""
        self._lines = []
    
    def add_comment(self, comment: str):
        """Add a comment line to the script.
        
        Args:
            comment: The comment text.
        """
        self._lines.append(f"// {comment}")
    
    def add_blank_line(self):
        """Add a blank line to the script."""
        self._lines.append("")
    
    def add_raw(self, code: str):
        """Add raw JavaScript code to the script.
        
        Args:
            code: The code to add.
        """
        self._lines.append(code)
    
    def create_scene(self, var_name: str = "scene"):
        """Add code to create a new scene.
        
        Args:
            var_name: Variable name for the scene.
        """
        self._lines.append(f"{var_name} = new Scene();")
    
    def save_scene(self, var_name: str, output_path: str):
        """Add code to save a scene.
        
        Args:
            var_name: Variable name of the scene.
            output_path: Path to save the scene to.
        """
        # Escape backslashes for JavaScript string
        escaped_path = output_path.replace("\\", "\\\\")
        self._lines.append(f'{var_name}.save("{escaped_path}");')
    
    def print_message(self, message: str):
        """Add a print statement for debugging/status.
        
        Args:
            message: Message to print.
        """
        self._lines.append(f'print("{message}");')
    
    def new_level(self, scene_var: str, level_var: str, level_type: str, level_name: str):
        """Add code to create a new level in a scene.
        
        Args:
            scene_var: Variable name of the scene.
            level_var: Variable name for the new level.
            level_type: Type of level ("Vector", "Raster", "ToonzRaster").
            level_name: Name for the level.
        """
        self._lines.append(f'{level_var} = {scene_var}.newLevel("{level_type}", "{level_name}");')
    
    def load_level(self, scene_var: str, level_var: str, level_name: str, file_path: str):
        """Add code to load a level into a scene.
        
        Args:
            scene_var: Variable name of the scene.
            level_var: Variable name for the loaded level.
            level_name: Name for the level in the scene.
            file_path: Path to the level file (can use ".." for frame number).
        """
        escaped_path = file_path.replace("\\", "\\\\")
        self._lines.append(f'{level_var} = {scene_var}.loadLevel("{level_name}", "{escaped_path}");')
    
    def set_cell(self, scene_var: str, row: int, col: int, level_var: str, frame_id):
        """Add code to set a cell in the xsheet.
        
        Args:
            scene_var: Variable name of the scene.
            row: Row index (0-based).
            col: Column index (0-based).
            level_var: Variable name of the level.
            frame_id: Frame ID to place in the cell.
        """
        self._lines.append(f'{scene_var}.setCell({row}, {col}, {level_var}, {frame_id});')
    
    def get_script(self) -> str:
        """Get the complete script as a string.
        
        Returns:
            The complete ToonzScript code.
        """
        return "\n".join(self._lines)
    
    def save_script(self, file_path: str):
        """Save the script to a file.
        
        Args:
            file_path: Path to save the script to.
        """
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(self.get_script())


def generate_blank_scene_script(output_tnz_path: str) -> str:
    """Generate a ToonzScript that creates a blank scene.
    
    Args:
        output_tnz_path: Path where the .tnz scene should be saved.
        
    Returns:
        The ToonzScript code as a string.
    """
    gen = ToonzScriptGenerator()
    
    gen.add_comment("OpenToonz Scene Creation Script")
    gen.add_comment("Generated by Krita OpenToonz Exporter")
    gen.add_blank_line()
    
    gen.add_comment("Create a new empty scene")
    gen.create_scene("scene")
    gen.add_blank_line()
    
    gen.add_comment("Save the scene")
    gen.save_scene("scene", output_tnz_path)
    gen.add_blank_line()
    
    gen.print_message("Scene created successfully!")
    
    return gen.get_script()


def generate_scene_with_levels_script(
    output_tnz_path: str,
    layer_infos: list
) -> str:
    """Generate a ToonzScript that creates a scene with levels and timing.
    
    Args:
        output_tnz_path: Path where the .tnz scene should be saved.
        layer_infos: List of LayerExportInfo objects containing level data.
        
    Returns:
        The ToonzScript code as a string.
    """
    gen = ToonzScriptGenerator()
    
    gen.add_comment("OpenToonz Scene Creation Script")
    gen.add_comment("Generated by Krita OpenToonz Exporter")
    gen.add_blank_line()
    
    gen.add_comment("Create a new scene")
    gen.create_scene("scene")
    gen.add_blank_line()
    
    # Load each level and set up xsheet timing
    # Reverse column assignment so visual order (left-to-right) matches Krita's layer panel (top-to-bottom)
    # while maintaining correct rendering order (lower columns = back, higher columns = front)
    num_layers = len(layer_infos)
    for i, layer_info in enumerate(layer_infos):
        col_index = num_layers - 1 - i  # Reverse: first layer -> highest column
        level_var = f"level{i}"
        
        gen.add_comment(f"Load level: {layer_info.name}")
        
        # Build the path to the level sequence
        # OpenToonz expects path with ".." for frame number placeholder
        level_path = os.path.join(layer_info.folder_path, layer_info.file_pattern)
        gen.load_level("scene", level_var, layer_info.name, level_path)
        
        gen.add_blank_line()
        gen.add_comment(f"Set xsheet timing for {layer_info.name} (column {col_index})")
        
        # Set each cell in the xsheet
        for xsheet_row, frame_id in layer_info.frame_data:
            gen.set_cell("scene", xsheet_row, col_index, level_var, frame_id)
        
        gen.add_blank_line()
    
    gen.add_comment("Save the scene")
    gen.save_scene("scene", output_tnz_path)
    gen.add_blank_line()
    
    gen.print_message("Scene created successfully!")
    
    return gen.get_script()
